In [31]:
import numpy as np
from scipy.fftpack import fft, ifft
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
y = fft(x)
y

array([ 4.50000000+0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [3]:
yinv = ifft(y)
yinv

array([ 1.0+0.j,  2.0+0.j,  1.0+0.j, -1.0+0.j,  1.5+0.j])

In [ ]:
import numpy as np
from scipy.fftpack import fft
N = 600
T = 1.0 / 800.0
x = np.linspace(0.0, N*T, N)
y = np.sin(50.0 * 2.0*np.pi*x) + 0.5*np.sin(80.0 * 2.0*np.pi*x)
yf = fft(y)
xf = np.linspace(0.0, 1.0/(2.0*T), N/2)
import matplotlib.pyplot as plt
plt.plot(xf, 2.0/N * np.abs(yf[0:N/2]))
plt.grid()
plt.show()

//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [ ]:
plt.plot(x,y)

In [1]:
import numpy as np
from scipy.fftpack import fft
N = 600
T = 1.0 / 800.0
x = np.linspace(0.0, N*T, N)

In [6]:
import matplotlib.pyplot as plt
plt.plot(x,y)

//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [7]:
plt.show()

In [1]:
import numpy as np
import pandas as pd
df1 = pd.read_csv('allquakes.csv', dtype=object)
df1

cluster   depth  Latitude  Longitude  mag startday startmonth  \
0            5     0.0     57.09    -153.48  8.3       10         10   
1            5     0.0      60.0     -135.0  7.1       18          1   
2            5     0.0      52.0     -160.0  6.6       30         12   
3            5     0.0     51.45    -171.02  7.8       31         12   
4            5     0.0     52.38    -167.45  7.8        1          1   
5            5     0.0     50.85    -175.16  7.0       17          1   
6            5     0.0      52.0      175.0  6.8        5          2   
7            5     0.0     61.56    -158.54  8.3        2          6   
8            5     0.0     64.62    -148.23  7.8       27          8   
9            5     0.0     50.73    -178.55  7.7       14          2   
10           5     0.0     51.28     174.83  7.2       22          3   
11           7     0.0     52.06     171.45  7.4       15          9   
12           5     0.0     53.88    -161.68  7.0       10         12   
13           5     0.0     50.77     179.73  8.0       17          8   
14           5     0.0      53.0     -165.0  7.6       23         12   
15           5   120.0      57.0     -161.0  6.5       22          8   
16           7     0.0     52.44     170.28  7.7        2          9   
17           5    25.0      59.0     -141.0  7.1       15          5   
18           5     0.0      52.0      175.0  7.0       10          4   
19           5    90.0      52.5     -169.0  7.4        8          9   
20           5     0.0      60.0     -149.5  7.4       19          9   
21           5   100.0      57.0     -160.0  6.7       13          5   
22           0     NaN      42.0     -127.0  6.8        5          8   
23           5    25.0     50.75     179.38  7.3        9          9   
24           5     0.0      53.0     -135.0  6.8        6         11   
25           0     NaN     37.25    -121.75  6.6        1          7   
26           5     0.0      51.0      180.0  7.1       17          9   
27           5    60.0      60.5     -149.0  6.9       22          9   
28           7     0.0      52.0      173.0  7.0       13         11   
29           5    25.0      52.0     -179.0  7.1        4          1   
...        ...     ...       ...        ...  ...      ...        ...   
617829      11  591.48   -21.541  -179.1091  4.6        4          7   
617830      11    6.56  -21.3093   168.6738  4.9        4          7   
617831      13    10.0   39.5984     73.068  4.2        4          7   
617832       7     9.1   29.6131   143.3523  4.6        4          7   
617833       6   43.29   -2.1018    138.966  4.4        4          7   
617834       3   93.55  -20.6978   -69.1784  4.7        4          7   
617835       0   31.94   16.6123   -97.8297  4.3        4          7   
617836       7    35.0   46.8062   152.8785  4.4        4          7   
617837       3    11.2  -20.1948   -70.9115  5.0        5          7   
617838       0    9.11   36.1518   -89.6965  3.0        5          7   
617839       8   98.55   24.8082    95.2124  4.4        5          7   
617840       6    35.0   -0.2665   125.5466  4.5        5          7   
617841       7    10.0   35.5119   129.8661  4.8        5          7   
617842       6    35.0   -0.3386   125.4749  4.4        5          7   
617843       5    10.0   43.3325  -126.6572  3.1        5          7   
617844       1   36.21   21.8613   145.3276  5.2        5          7   
617845      13   155.4   38.2305    73.6797  4.3        5          7   
617846       0     5.0   36.2626   -97.5821  3.5        5          7   
617847       3   39.51  -41.6855   -74.0542  4.3        5          7   
617848      11    10.0   -32.927  -177.8664  5.2        5          7   
617849       6  192.36    2.0851   128.3228  4.3        5          7   
617850       0     5.0   37.3679   -98.2025  3.5        5          7   
617851      13    10.0    39.489    73.4459  4.4        5          7   
617852       7   29.15   29.7514   142.1428  4.

In [64]:
df1['mag'] = pd.to_numeric(df1['mag'])
df2 = df1['startyear'][(df1['cluster'] == '14') &(df1['mag'] >= 5)].value_counts()
#

In [65]:
df2 = pd.DataFrame(df2)
df2

startyear
1976        116
2007        116
1983        110
2010        109
2014        106
2005        105
1979        104
2009        101
1974        100
1988         99
1992         99
1990         96
1982         95
1991         91
2012         90
2008         90
2015         86
2006         85
1985         84
1995         82
2004         81
1997         80
1970         79
1978         79
1984         77
1969         77
2001         76
2011         75
1965         75
1977         72
1981         72
1968         71
1973         71
2002         70
2000         69
1989         68
1980         68
1996         66
1986         63
1987         63
1999         62
1998         61
1975         60
1994         59
2016         56
1971         56
1972         54
2013         52
1966         51
2003         50
1967         50
1993         49
1964         48
1963         39
1962          3

In [66]:
df2['count'] = df2['startyear']
del df2['startyear']
df2.to_csv('count.csv')

In [67]:
import numpy as np
import pandas as pd
from scipy.fftpack import fft, ifft
df = pd.read_csv('count.csv', dtype=object)

In [68]:
df = df.sort(['year'])
df.index = range(len(df))
df['year'] = pd.to_numeric(df['year'])
df['count'] = pd.to_numeric(df['count'])
df = df[(df['year'] >= 1963) & (df['year'] <= 2015)]
#
x = df['year'].values
y = df['count'].values

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


In [46]:
#df = df.append({'year':1984, 'count':0}, ignore_index=True)

In [69]:
import scipy.fftpack
yf = scipy.fftpack.fft(y)

In [70]:
yf

array([  4.10700000e+03  +0.j        ,  -6.28756245e+01 +24.59824353j,
        -9.74347463e+01+315.46898501j,  -1.69650495e+02+142.07542797j,
        -5.15371647e+01 -65.93984598j,  -3.03656632e+01 -20.28761149j,
         5.19189798e+01 -22.4691426j ,  -8.42524398e+01+186.94359159j,
         1.11365962e+02 +40.31099278j,  -4.20239026e+01 +29.66392468j,
         6.00289681e+01 -16.24518032j,   1.96928342e+00 +38.78138057j,
        -2.51102465e+02 +41.41405265j,  -4.01391697e+01 +39.04414328j,
        -1.17219328e+02 +22.03776389j,  -5.58943919e+01 +89.15663257j,
        -9.02070827e+01 +87.01938603j,   1.21899715e+00-141.9297951j ,
        -1.55793258e+02 +61.76076886j,  -1.79143553e+01+147.76279071j,
        -7.48845645e+00 +40.71307114j,  -1.15146923e+02 -54.10348482j,
        -7.82171617e+01-183.59756151j,   1.99656431e+01 +99.20669802j,
         1.45183731e+02-103.73726814j,   6.79360253e+01 -27.16318434j,
        -1.23249629e+01 -57.23833607j,  -1.23249629e+01 +57.23833607j,
      

In [71]:
len(yf)

53

In [72]:
xf = np.linspace(0.0, 0.5, 53/2)

In [73]:
import matplotlib.pyplot as plt
plt.plot(xf, 2.0/53 * np.abs(yf[0:53/2]))

In [74]:
plt.grid()
plt.show()