In [2]:
import numpy as np
from scipy.fftpack import fft, ifft
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
y = fft(x)
y

array([ 4.50000000+0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

In [3]:
yinv = ifft(y)
yinv

array([ 1.0+0.j,  2.0+0.j,  1.0+0.j, -1.0+0.j,  1.5+0.j])

In [ ]:
import numpy as np
from scipy.fftpack import fft
N = 600
T = 1.0 / 800.0
x = np.linspace(0.0, N*T, N)
y = np.sin(50.0 * 2.0*np.pi*x) + 0.5*np.sin(80.0 * 2.0*np.pi*x)
yf = fft(y)
xf = np.linspace(0.0, 1.0/(2.0*T), N/2)
import matplotlib.pyplot as plt
plt.plot(xf, 2.0/N * np.abs(yf[0:N/2]))
plt.grid()
plt.show()

//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [ ]:
plt.plot(x,y)

In [1]:
import numpy as np
from scipy.fftpack import fft
N = 600
T = 1.0 / 800.0
x = np.linspace(0.0, N*T, N)

In [6]:
import matplotlib.pyplot as plt
plt.plot(x,y)

//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [7]:
plt.show()

In [8]:
import numpy as np
import pandas as pd
df1 = pd.read_csv('allquakes.csv', dtype=object)
df1

cluster   depth  Latitude  Longitude  mag startday startmonth  \
0            5     0.0     57.09    -153.48  8.3       10         10   
1            5     0.0      60.0     -135.0  7.1       18          1   
2            5     0.0      52.0     -160.0  6.6       30         12   
3            5     0.0     51.45    -171.02  7.8       31         12   
4            5     0.0     52.38    -167.45  7.8        1          1   
5            5     0.0     50.85    -175.16  7.0       17          1   
6            5     0.0      52.0      175.0  6.8        5          2   
7            5     0.0     61.56    -158.54  8.3        2          6   
8            5     0.0     64.62    -148.23  7.8       27          8   
9            5     0.0     50.73    -178.55  7.7       14          2   
10           5     0.0     51.28     174.83  7.2       22          3   
11           7     0.0     52.06     171.45  7.4       15          9   
12           5     0.0     53.88    -161.68  7.0       10         12   
13           5     0.0     50.77     179.73  8.0       17          8   
14           5     0.0      53.0     -165.0  7.6       23         12   
15           5   120.0      57.0     -161.0  6.5       22          8   
16           7     0.0     52.44     170.28  7.7        2          9   
17           5    25.0      59.0     -141.0  7.1       15          5   
18           5     0.0      52.0      175.0  7.0       10          4   
19           5    90.0      52.5     -169.0  7.4        8          9   
20           5     0.0      60.0     -149.5  7.4       19          9   
21           5   100.0      57.0     -160.0  6.7       13          5   
22           0     NaN      42.0     -127.0  6.8        5          8   
23           5    25.0     50.75     179.38  7.3        9          9   
24           5     0.0      53.0     -135.0  6.8        6         11   
25           0     NaN     37.25    -121.75  6.6        1          7   
26           5     0.0      51.0      180.0  7.1       17          9   
27           5    60.0      60.5     -149.0  6.9       22          9   
28           7     0.0      52.0      173.0  7.0       13         11   
29           5    25.0      52.0     -179.0  7.1        4          1   
...        ...     ...       ...        ...  ...      ...        ...   
617829      11  591.48   -21.541  -179.1091  4.6        4          7   
617830      11    6.56  -21.3093   168.6738  4.9        4          7   
617831      13    10.0   39.5984     73.068  4.2        4          7   
617832       7     9.1   29.6131   143.3523  4.6        4          7   
617833       6   43.29   -2.1018    138.966  4.4        4          7   
617834       3   93.55  -20.6978   -69.1784  4.7        4          7   
617835       0   31.94   16.6123   -97.8297  4.3        4          7   
617836       7    35.0   46.8062   152.8785  4.4        4          7   
617837       3    11.2  -20.1948   -70.9115  5.0        5          7   
617838       0    9.11   36.1518   -89.6965  3.0        5          7   
617839       8   98.55   24.8082    95.2124  4.4        5          7   
617840       6    35.0   -0.2665   125.5466  4.5        5          7   
617841       7    10.0   35.5119   129.8661  4.8        5          7   
617842       6    35.0   -0.3386   125.4749  4.4        5          7   
617843       5    10.0   43.3325  -126.6572  3.1        5          7   
617844       1   36.21   21.8613   145.3276  5.2        5          7   
617845      13   155.4   38.2305    73.6797  4.3        5          7   
617846       0     5.0   36.2626   -97.5821  3.5        5          7   
617847       3   39.51  -41.6855   -74.0542  4.3        5          7   
617848      11    10.0   -32.927  -177.8664  5.2        5          7   
617849       6  192.36    2.0851   128.3228  4.3        5          7   
617850       0     5.0   37.3679   -98.2025  3.5        5          7   
617851      13    10.0    39.489    73.4459  4.4        5          7   
617852       7   29.15   29.7514   142.1428  4.

In [47]:
df2 = df1['startyear'].value_counts()

In [48]:
df2 = pd.DataFrame(df2)

In [49]:
df2['count'] = df2['startyear']
del df2['startyear']

In [31]:
df2.to_csv('count.csv')

In [4]:
import numpy as np
import pandas as pd
from scipy.fftpack import fft, ifft
df = pd.read_csv('count.csv', dtype=object)

In [6]:
df = df.sort(['year'])
df.index = range(len(df))
df['year'] = pd.to_numeric(df['year'])
df['count'] = pd.to_numeric(df['count'])
x = df['year'].values
y = df['count'].values

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


In [8]:
import scipy.fftpack
yf = scipy.fftpack.fft(y)

In [9]:
yf

array([  6.17859000e+05     +0.j        ,
         2.17978996e+05+392931.76590705j,
         4.28293140e+03+213709.70829271j,
        -2.78141425e+04+179447.2847878j ,
        -7.50847506e+04 +78878.87758053j,
        -3.31606326e+04 +58733.04576953j,
        -5.08466833e+04 +30904.03535046j,
        -1.58944161e+04 +16804.29863921j,
        -2.74906374e+04  +8045.68861334j,
         9.72667989e+03  -2789.3837679j ,
         1.37275390e+04 +16639.52436455j,
         2.65557814e+04 +30094.00414622j,
        -1.87776197e+03 +53247.2384106j ,
        -1.11836685e+04 +37531.22641217j,
        -2.29951530e+04 +42188.50230647j,
        -2.88251703e+04 +18316.64615613j,
        -2.42822537e+04 +22419.00308649j,
        -3.06109789e+04  +5418.95496349j,
        -1.33943184e+04  +3567.69105215j,
        -1.97574924e+04  +4515.65640627j,
        -9.88750963e+03   +812.33844145j,
        -1.10430437e+04  +1229.68884051j,
         2.09884885e+03  +3282.87235982j,
        -6.93751122e+03 +17290.627

In [10]:
len(yf)

117

In [11]:
xf = np.linspace(0.0, 0.5, 58.5)

In [12]:
xf

array([ 0.        ,  0.00877193,  0.01754386,  0.02631579,  0.03508772,
        0.04385965,  0.05263158,  0.06140351,  0.07017544,  0.07894737,
        0.0877193 ,  0.09649123,  0.10526316,  0.11403509,  0.12280702,
        0.13157895,  0.14035088,  0.14912281,  0.15789474,  0.16666667,
        0.1754386 ,  0.18421053,  0.19298246,  0.20175439,  0.21052632,
        0.21929825,  0.22807018,  0.23684211,  0.24561404,  0.25438596,
        0.26315789,  0.27192982,  0.28070175,  0.28947368,  0.29824561,
        0.30701754,  0.31578947,  0.3245614 ,  0.33333333,  0.34210526,
        0.35087719,  0.35964912,  0.36842105,  0.37719298,  0.38596491,
        0.39473684,  0.40350877,  0.4122807 ,  0.42105263,  0.42982456,
        0.43859649,  0.44736842,  0.45614035,  0.46491228,  0.47368421,
        0.48245614,  0.49122807,  0.5       ])

In [14]:
import matplotlib.pyplot as plt
plt.plot(xf, 2.0/117 * np.abs(yf[0:117/2]))

//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [15]:
plt.grid()
plt.show()

KeyboardInterrupt: 